[server]
maxUploadSize = 30
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#3b82f6"
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#ffffff"

